version = 1

[[annotations]]
path = "img/*"
SPDX-FileCopyrightText = [
	"2010-2025 GNOME Project",
	"2025 Sofian-Hedi Krazini <blackma9ick@proton.me>",
]
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "subprojects/*"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
